### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by MrSpiffyClean** [MrSpiffyClean/covidtrends#2]
Basic to-do list, in order to document remaining changes.

- [x] Change changeURL in order to detect whether defaults have been set
- [x] Deal with Select All / Deselect All buttons (first idea is having just a new URL parameter with select=all/none)
- [x] Investigate weird performance issue (seems slower now than just calling changeURL without arguments) with how I'm now calling changeURL

2020-05-07
- [x] Changing Region after selecting all doesn't update correctly the URL (the url still thinks everything is selected, even though it is not)
- [x] Making Vue.js recognize the new `select` parameter

**Comment by MrSpiffyClean** [comment]
In order to check if defaults have been changed, look into how processData sets the default countries (line 439) and adapt from there.

**Comment by MrSpiffyClean** [comment]
:heavy_check_mark: Change changeURL in order to detect whether defaults have been set
~~Need to test this to check if works/borks stuff.~~
- ~~De-selecting a country that's on the default list doesn't update the url, because the code only checks if countries are on the default list or not, which means if they are all part of the list, the code doesn't update.~~
- Checked the _performance issue_ using the Performance Tester on Firefox, it seems whenever I press a checkbox, there are either lengthy DOM update events or GC collection/usage.

**Comment by MrSpiffyClean** [comment]
New idea. Having a button to restore to defaults (in the middle of the select all / deselect all). Since pressing a region and then going back restores the default, maybe not needed.

**Comment by MrSpiffyClean** [comment]
:heavy_check_mark: Investigate weird performance issue (seems slower now than just calling changeURL without arguments) with how I'm now calling changeURL

Remembered to check the actual live page if my perceived performance issue (slight 1 second pause between button presses) was there and it turns out it is, which means my code isn't directly responsible for it. It is something to look into forward.

**Comment by MrSpiffyClean** [comment]
:heavy_check_mark: Deal with Select All / Deselect All buttons (first idea is having just a new URL parameter with select=all/none)
The buttons have the basic functionality, however two things need to be solved before the pull request:

- Changing Region after selecting all doesn't update correctly the URL (the url still thinks everything is selected, even though it is not)
- Making Vue.js recognize the new `select` parameter

The tasks were added to the first post.

**Comment by MrSpiffyClean** [comment]
The createURL event seems to fire _before_ the actual renderization/selection of the buttons/countries. Using the checkbox variable to halt all being added should work.

**Comment by MrSpiffyClean** [comment]
:heavy_check_mark: Changing Region after selecting all doesn't update correctly the URL (the url still thinks everything is selected, even though it is not)
:heavy_check_mark: Making Vue.js recognize the new select parameter

**Comment by MrSpiffyClean** [comment]
The code should now be ready for a pull request. Tomorrow, after some basic checks.

In case I decide to add the "restore to defaults" button, a thing of note is that changing the selectedCountries array also changes everything else, so that's pretty much how to do it.
